name: Android CI

on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]
    
    
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Running Lint
        run: ./gradlew lintDebug
          
      - name: Upload Lint Test Report
        uses: actions/upload-artifact@v2
        with:
         name: lint.html
         path: app/build/reports/lint-results-debug.html
              
  unit-test:
   needs: [lint]
   runs-on: ubuntu-latest
   steps:
     - name: Checkout the code
       uses: actions/checkout@v2
      
     - name: Running unit tests
       run: ./gradlew test --stacktrace
          
     - name: Upload Unit Tests Report
       uses: actions/upload-artifact@v2
       with:
             name: unit-test-report
             path: app/build/reports//test/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: 'x86_64'
          api-level: 30
          script: ./gradlew connectedCheck --stacktrace
      
      - name: Upload Instrumentation Test report
        uses: actions/upload-artifact@v2
        with:
              name: instrumentation_test_report
              path: app/build/reports/androidTests/connected/
              
  static-code-analysis:
      needs: [instrumentation-test]
      runs-on: ubuntu-latest
      steps:
        - name: Checkut the code
          uses: actions/checkout@v2
          
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
              java-version: 11
            
        - name: SonarCloud Scan
          run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }} --stacktrace
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
