name: Build APK on Merge

on:

  workflow_dispatch:
  
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build APK
        run: ./gradlew assembleRelease

      # Optionally, upload the APK as an artifact
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
