name: Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.generate-changelog.outputs.changelog }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Generate Changelog
        id: generate-changelog
        uses: TriPSs/conventional-changelog-action@v5.2.0
        with:
          preset: conventionalcommits

  create-release:
    needs: generate-changelog
    runs-on: ubuntu-latest
    if: ${{ !contains(needs.generate-changelog.outputs.changelog, '[skip-release]') }}
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ""
          tag_name: ${{ needs.generate-changelog.outputs.tag }}
          name: ${{ needs.generate-changelog.outputs.tag }}
          body: ${{ needs.generate-changelog.outputs.clean_changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
