name: Releases
on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:

  skip-workflow:
    runs-on: ubuntu-latest
    
    outputs: # job outputs
      skip: ${{ steps.skip-workflow.outputs.skip }}
    
    steps:
      - uses: actions/checkout@v3

      - name: skip-workflow
        id: skip-workflow # id used for referencing step
        uses: saulmaldonado/skip-workflow@v1
        with:
          phrase: '[skip-release]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          
  changelog:
  
    needs: skip-workflow
    
    if: ${{ !needs.skip-workflow.outputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          preset: conventionalcommits
          
      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
